(()=>{'use strict';
const $=id=>document.getElementById(id);const c=$('canvas'),x=c.getContext('2d');let dpr=1,W=innerWidth,H=innerHeight;const TILE=38,keys=new Set();let me=null,player={x:7,y:7,vx:0,vy:0,ground:false,face:1},cam=0,worlds=[],chatOpen=false;const blocks=new Map();
const B={grass:'#59d17d',dirt:'#9a6545',stone:'#7f8795',wood:'#9d6b46',leaf:'#399a57',brick:'#b45b51',crystal:'#5ce0f0'};function K(a,b){return a+','+b}function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;c.width=W*dpr;c.height=H*dpr;x.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
function gen(){blocks.clear();for(let i=-40;i<55;i++){let top=9+Math.floor(Math.sin(i*.18)*1.5);for(let y=0;y<=top;y++)blocks.set(K(i,y),{type:y===top?'grass':y>top-3?'dirt':'stone'});if(i%9===0){blocks.set(K(i,top+1),{type:'wood'});blocks.set(K(i,top+2),{type:'wood'});for(let dx=-2;dx<=2;dx++)for(let dy=3;dy<=4;dy++)blocks.set(K(i+dx,top+dy),{type:'leaf'})}}player.x=5;player.y=11;player.vx=0;player.vy=0}
function wy(y){return H-75-y*TILE}function wx(i){return W/2+(i-cam)*TILE}function draw(){let g=x.createLinearGradient(0,0,0,H);g.addColorStop(0,'#8ddfff');g.addColorStop(1,'#f6c9f1');x.fillStyle=g;x.fillRect(0,0,W,H);x.fillStyle='#ffffff66';for(let i=0;i<7;i++){let xx=((i*270-cam*10)%(W+300))-120;let yy=105+(i%3)*55;x.beginPath();x.arc(xx,yy,18,0,7);x.arc(xx+22,yy-4,23,0,7);x.arc(xx+48,yy+2,17,0,7);x.fill()}for(const [k,b] of blocks){let [px,py]=k.split(',').map(Number),sx=wx(px),sy=wy(py);if(sx<-TILE||sx>W+TILE)continue;x.fillStyle=B[b.type]||'#aaa';x.fillRect(sx+1,sy+1,TILE-2,TILE-2);x.fillStyle='#ffffff22';x.fillRect(sx+2,sy+2,TILE-4,5);if(b.type==='grass'){x.fillStyle='#299b58';x.fillRect(sx+2,sy+1,TILE-4,5)}}const sx=wx(player.x)-13,sy=wy(player.y)-58;x.fillStyle='#28213f';x.fillRect(sx+5,sy+28,18,29);x.fillStyle='#ef7cda';x.fillRect(sx+3,sy+9,22,21);x.fillStyle='#151022';x.fillRect(sx+(player.face>0?18:4),sy+15,4,4);x.fillStyle='#63ddff';x.fillRect(sx+6,sy+57,6,8);x.fillRect(sx+17,sy+57,6,8);x.fillStyle='#12101d';x.font='800 10px Inter';x.textAlign='center';x.fillText(me?.username||'Explorer',wx(player.x),sy-3);x.textAlign='left'}
function solid(px,py){return blocks.has(K(Math.floor(px),Math.floor(py)))}function coll(px,py){for(let xx=Math.floor(px-.3);xx<=Math.floor(px+.3);xx++)for(let yy=Math.floor(py);yy<=Math.floor(py+1.5);yy++)if(solid(xx,yy))return true;return false}
function loop(){let dt=.016;if(keys.has('a')){player.vx-=.8;player.face=-1}if(keys.has('d')){player.vx+=.8;player.face=1}player.vx*=.86;player.vx=Math.max(-5,Math.min(5,player.vx));player.vy-=.55;if(keys.has(' ')&&player.ground){player.vy=10;player.ground=false}let nx=player.x+player.vx*dt;if(!coll(nx,player.y))player.x=nx;let ny=player.y+player.vy*dt;if(!coll(player.x,ny)){player.y=ny;player.ground=false}else{if(player.vy<0){player.y=Math.floor(ny)+1;player.ground=true}player.vy=0}cam+=(player.x-cam)*.12;draw();requestAnimationFrame(loop)}
function modal(title,eyebrow,content){$('eyebrow').textContent=eyebrow;$('title').textContent=title;$('content').innerHTML=content;$('modal').classList.add('open')}
function close(){ $('modal').classList.remove('open') }
async function api(url,opt={}){const r=await fetch(url,{credentials:'include',...opt});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Request failed');return d}
async function load(){try{const d=await api('/api/auth/me');me=d.user;if(!me){location.href='./';return}$('display').textContent=me.displayName||me.username;$('handle').textContent='@'+me.username;$('avatar').textContent=(me.displayName||me.username||'V')[0].toUpperCase();}catch{location.href='./';}gen();try{const d=await api('/api/worlds');worlds=d.worlds||[]}catch{}}
function showWorlds(){const rows=worlds.length?worlds.map(w=>`<div class="world"><div><strong>${esc(w.name)}</strong><small>${w.type} · ${w.privacy==='public'?'Public':'Private'} · @${esc(w.ownerUsername||'owner')}</small></div><button onclick="location.href='./world.html?id=${encodeURIComponent(w.id)}'">ENTER</button></div>`).join(''):'<div class="msg">No worlds yet.</div>';modal('Worlds','EXPLORE',rows+'<div class="grid"><button class="action primary" onclick="location.href=\'./worlds.html\'">CREATE / MANAGE WORLDS</button></div>')}
function showProfile(){modal('Character','YOUR PROFILE',`<div class="action">👤 <b>@${esc(me.username)}</b><br><span class="msg">Customize your character and profile.</span></div><button class="action primary" onclick="location.href='./profile.html'">OPEN PROFILE</button>`)}
function showMenu(){modal('Menu','VEXORA',`<button class="action" onclick="location.reload()">↻ Return to character</button><button class="action" onclick="location.href='./worlds.html'">🌎 Worlds</button><button class="action" onclick="location.href='./profile.html'">👤 Profile</button><button class="action" onclick="logout()">↪ Log out</button>`)}
async function logout(){try{await fetch('/api/auth/logout',{method:'POST',credentials:'include'})}finally{location.href='./'}}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])}
$('worldsBtn').onclick=showWorlds;$('profileBtn').onclick=showProfile;$('menuBtn').onclick=showMenu;$('close').onclick=close;$('modal').onclick=e=>{if(e.target===$('modal'))close()};
$('chatBtn').onclick=()=>{chatOpen=!chatOpen;$('chat').style.display=chatOpen?'block':'none';if(chatOpen)$('chatInput').focus()};$('chatForm').onsubmit=e=>{e.preventDefault();const v=$('chatInput').value.trim();if(v){const r=document.createElement('div');r.className='row';r.innerHTML='<b>@'+esc(me.username)+'</b> '+esc(v);$('msgs').appendChild(r);$('chatInput').value=''}};
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['a','d',' '].includes(k))keys.add(k);if(k==='e'){showProfile()}if(k==='t'){$('chatBtn').click()}if(k==='escape'){close();$('chat').style.display='none'}});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
load().then(()=>requestAnimationFrame(loop));
window.logout=logout;
})();