const worldList=document.getElementById('worldList'),worldModal=document.getElementById('worldModal'),worldMessage=document.getElementById('worldMessage');let lobbyLast=0,lobbyRead=null;
const escapeHtml=v=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const worldTypeLabel=t=>({normal:'🌎 Normal',creative:'✨ Creative',adventure:'⚔️ Adventure'}[t]||'🌎 Normal');
function worldCard(w){return `<article class="world-card world-card-v2"><div class="world-icon">✦</div><div class="world-info"><strong>${escapeHtml(w.name)}</strong><p>${worldTypeLabel(w.type)} · ${w.privacy==='public'?'🌐 Public':'🔒 Private'}${w.ownerUsername?` · @${escapeHtml(w.ownerUsername)}`:''}</p></div><a class="secondary-button world-enter" href="./world.html?id=${encodeURIComponent(w.id)}">ENTER WORLD <span>→</span></a></article>`}
async function loadWorlds(){try{const r=await fetch('/api/worlds',{credentials:'include'}),d=await r.json();if(!r.ok)throw Error(d.error||'Unable to load worlds.');const worlds=d.worlds||[];if(!worlds.length){worldList.innerHTML='<div class="empty-world world-empty"><div class="plus">+</div><div><strong>Your first world is waiting.</strong><p>Create a world and make it your own.</p></div><button id="emptyCreateWorld" class="secondary-button create-world">CREATE FIRST WORLD</button></div>';document.getElementById('emptyCreateWorld')?.addEventListener('click',openWorldModal);return}worldList.innerHTML=worlds.map(worldCard).join('')}catch(e){worldList.innerHTML=`<div class="world-error">${escapeHtml(e.message)}</div>`}}
function openWorldModal(){worldModal.hidden=false;worldMessage.textContent='';document.getElementById('worldName')?.focus()}function closeWorldModal(){worldModal.hidden=true}
async function createWorld(e){e.preventDefault();const button=e.currentTarget.querySelector('button[type=submit]'),name=document.getElementById('worldName').value.trim(),type=document.getElementById('worldType').value,privacy=document.getElementById('worldPrivacy').value;worldMessage.textContent='Creating your world…';button.disabled=true;try{const r=await fetch('/api/worlds',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({name,type,privacy})}),d=await r.json();if(!r.ok)throw Error(d.error||'Unable to create world.');closeWorldModal();e.currentTarget.reset();await loadWorlds()}catch(err){worldMessage.textContent=err.message}finally{button.disabled=false}}
function setAvatar(user){const avatar=document.getElementById('avatar');if(!avatar)return;if(user.avatarUrl){avatar.innerHTML=`<img src="${escapeHtml(user.avatarUrl)}" alt="">`;avatar.style.overflow='hidden';avatar.style.padding='0';avatar.querySelector('img').style.cssText='width:100%;height:100%;object-fit:cover;border-radius:inherit';}else{avatar.textContent=(user.displayName||user.username).charAt(0).toUpperCase();}}
async function loadAccount(){try{const r=await fetch('/api/auth/me',{credentials:'include'}),d=await r.json();if(!r.ok||!d.authenticated){location.href='./';return}const u=d.user;window.__vexoraUserId=u.id;document.getElementById('displayName').textContent=u.displayName||u.username;document.getElementById('profileName').textContent=u.displayName||u.username;document.getElementById('profileUsername').textContent=`@${u.username}`;document.getElementById('profileEmail').textContent=u.email;setAvatar(u);await loadWorlds();await pollLobby();setInterval(pollLobby,2500)}catch{location.href='./'}}
async function pollLobby(){if(lobbyRead)return;const url=`/api/chat?after=${lobbyLast}`;lobbyRead=fetch(url,{credentials:'include'}).then(async r=>{const d=await r.json();if(!r.ok)return;const box=document.getElementById('lobbyChatMessages');for(const m of d.messages||[]){lobbyLast=m.id;const row=document.createElement('div');row.className='chat-line';row.dataset.messageId=m.id;row.innerHTML=`<b>@${escapeHtml(m.username)}</b><span>${escapeHtml(m.message)}</span>`;if(!box.querySelector(`[data-message-id="${m.id}"]`))box.appendChild(row)}box.scrollTop=box.scrollHeight}).catch(()=>{}).finally(()=>{lobbyRead=null})}
async function sendLobby(){const i=document.getElementById('lobbyChatInput'),m=i.value.trim();if(!m)return;i.value='';try{await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({message:m})});pollLobby()}catch{}}
document.getElementById('logoutButton')?.addEventListener('click',async()=>{await fetch('/api/auth/logout',{method:'POST',credentials:'include'});location.href='./'});document.getElementById('playButton')?.addEventListener('click',()=>document.getElementById('worlds').scrollIntoView({behavior:'smooth'}));document.getElementById('openCreateWorld')?.addEventListener('click',openWorldModal);document.getElementById('closeWorldModal')?.addEventListener('click',closeWorldModal);document.getElementById('createWorldForm')?.addEventListener('submit',createWorld);document.getElementById('lobbyChatSend')?.addEventListener('click',sendLobby);document.getElementById('lobbyChatInput')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();sendLobby()}});worldModal?.addEventListener('click',e=>{if(e.target===worldModal)closeWorldModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!worldModal.hidden)closeWorldModal()});loadAccount();
