const $ = id => document.getElementById(id);
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let currentUser = null;
let toastTimer;

async function api(url, options={}) {
  const response = await fetch(url, { credentials:'include', ...options });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error || `HTTP ${response.status}`);
  return data;
}
function toast(message) { const el=$('profileToast'); el.textContent=message; el.classList.add('show'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>el.classList.remove('show'),2200); }
function formatTime(seconds){seconds=Math.max(0,Math.floor(Number(seconds)||0));const d=Math.floor(seconds/86400),h=Math.floor(seconds%86400/3600),m=Math.floor(seconds%3600/60);if(d)return `${d}d ${h}h`;if(h)return `${h}h ${m}m`;return `${m}m`;}
function accountAge(created){const t=new Date(created).getTime();if(!Number.isFinite(t))return '—';const days=Math.max(0,Math.floor((Date.now()-t)/86400000));return `${days} ${days===1?'day':'days'}`;}
function avatarMarkup(user, cls='friend-avatar'){const initial=esc((user.displayName||user.username||'V').charAt(0).toUpperCase());return user.avatarUrl?`<div class="${cls}"><img src="${esc(user.avatarUrl)}" alt=""></div>`:`<div class="${cls}">${initial}</div>`;}
function renderUser(){const u=currentUser;if(!u)return;$('name').textContent=u.displayName||u.username;$('username').textContent='@'+u.username;$('email').textContent=u.email||'';$('accountAge').textContent=accountAge(u.createdAt);$('playTime').textContent=formatTime(u.totalPlaySeconds);$('avatar').innerHTML=u.avatarUrl?`<img src="${esc(u.avatarUrl)}" alt="${esc(u.username)}">`:esc((u.displayName||u.username||'V').charAt(0).toUpperCase());$('editName').value=u.displayName||u.username;$('avatarPreview').innerHTML=u.avatarUrl?`<img src="${esc(u.avatarUrl)}" alt="">`:esc((u.displayName||u.username||'V').charAt(0).toUpperCase());}
async function loadProfile(){const data=await api('/api/profile');currentUser=data.user;renderUser();}
function friendRow(user, action='add'){const actions=action==='add'?`<button data-user="${esc(user.id)}" class="add-friend">ADD</button>`:action==='accept'?`<button data-user="${esc(user.id)}" class="accept-friend">ACCEPT</button><button data-user="${esc(user.id)}" class="ghost reject-friend">DECLINE</button>`:action==='outgoing'?`<button data-user="${esc(user.id)}" class="ghost cancel-friend">CANCEL</button>`:`<button data-user="${esc(user.id)}" class="ghost remove-friend">REMOVE</button>`;return `<div class="friend-item">${avatarMarkup(user)}<div class="friend-info"><strong>${esc(user.displayName||user.username)}</strong><small>@${esc(user.username)}</small></div><div class="friend-actions">${actions}</div></div>`;}
async function loadFriends(){const data=await api('/api/friends');$('friendList').innerHTML=data.friends.length?data.friends.map(u=>friendRow(u,'friend')).join(''):'<div class="empty-pro">No friends yet. Search a username to start.</div>';$('incomingList').innerHTML=data.incoming.length?data.incoming.map(u=>friendRow(u,'accept')).join(''):'<div class="empty-pro">No pending requests.</div>';$('outgoingList').innerHTML=data.outgoing.length?data.outgoing.map(u=>friendRow(u,'outgoing')).join(''):'<div class="empty-pro">No outgoing requests.</div>';bindFriendActions();$('friendCount').textContent=data.friends.length;}
function bindFriendActions(){document.querySelectorAll('.add-friend').forEach(b=>b.onclick=async()=>{try{await api('/api/friends',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:b.closest('.friend-item').querySelector('small').textContent.slice(1)})});toast('Friend request sent');loadFriends();$('friendResults').innerHTML='';}catch(e){toast(e.message)}});document.querySelectorAll('.accept-friend').forEach(b=>b.onclick=async()=>{await api('/api/friends',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:b.dataset.user,action:'accept'})});toast('Friend added');loadFriends();});document.querySelectorAll('.reject-friend').forEach(b=>b.onclick=async()=>{await api('/api/friends',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:b.dataset.user,action:'reject'})});loadFriends();});document.querySelectorAll('.cancel-friend,.remove-friend').forEach(b=>b.onclick=async()=>{await api('/api/friends',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:b.dataset.user})});loadFriends();});}
async function searchFriends(){const q=$('friendSearch').value.trim();if(!q){$('friendResults').innerHTML='';return}try{const data=await api('/api/friends?search='+encodeURIComponent(q));$('friendResults').innerHTML=data.users.length?data.users.map(u=>friendRow(u,'add')).join(''):'<div class="empty-pro">No explorer found with that username.</div>';bindFriendActions();}catch(e){toast(e.message)}}
async function saveProfile(){const button=$('saveProfile');button.disabled=true;try{const data=await api('/api/profile',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({displayName:$('editName').value.trim(),avatarUrl:$('avatarData').value})});currentUser=data.user;renderUser();toast('Profile saved');}catch(e){toast(e.message)}finally{button.disabled=false}}
function readAvatar(file){if(!file)return;const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const size=256,canvas=document.createElement('canvas');canvas.width=size;canvas.height=size;const ctx=canvas.getContext('2d');const scale=Math.max(size/img.width,size/img.height),w=img.width*scale,h=img.height*scale;ctx.drawImage(img,(size-w)/2,(size-h)/2,w,h);const data=canvas.toDataURL('image/webp',.78);if(data.length>300000){toast('Photo is too large after compression');return}$('avatarData').value=data;$('avatarPreview').innerHTML=`<img src="${data}" alt="">`;};img.src=reader.result;};reader.readAsDataURL(file);}
function bind(){ $('saveProfile').onclick=saveProfile;$('avatarFile').onchange=e=>readAvatar(e.target.files[0]);$('friendSearch').addEventListener('input',()=>{clearTimeout(window.__friendTimer);window.__friendTimer=setTimeout(searchFriends,250)});$('friendSearch').addEventListener('keydown',e=>{if(e.key==='Enter')searchFriends();});}
(async()=>{try{const me=await api('/api/auth/me');if(!me.authenticated)return location.href='./';await loadProfile();await loadFriends();bind();}catch(e){console.error(e);location.href='./';}})();
