import * as THREE from 'https://esm.sh/three@0.180.0';

const $=id=>document.getElementById(id);
const params=new URLSearchParams(location.search), worldId=params.get('id');
const TYPES={grass:{name:'Grass',color:0x58c978,hard:.18},dirt:{name:'Dirt',color:0x8b5b3d,hard:.25},stone:{name:'Stone',color:0x7f8996,hard:.72},wood:{name:'Wood',color:0x9b6942,hard:.5},leaf:{name:'Leaves',color:0x349452,hard:.12},sand:{name:'Sand',color:0xd9bf7a,hard:.16},crystal:{name:'Vexa Crystal',color:0x55d9ef,hard:.9},gold:{name:'Vexa Ore',color:0xe4b63a,hard:1.1},glass:{name:'Glass',color:0x9de4f4,hard:.1},brick:{name:'Brick',color:0xa85249,hard:.62}};
const HOT=['grass','dirt','stone','wood','leaf','sand','crystal','gold','brick'];
const blocks=new Map(), keys=new Set(), remotes=new Map(), inventory=Object.fromEntries(Object.keys(TYPES).map(k=>[k,0]));
const K=(x,y,z)=>`${x},${y},${z}`;
let meta={name:'VEXORA WORLD',type:'creative',seed:1337},mode='creative',selected=0,started=false,paused=false,chatOpen=false,mining=false,mineTarget=null,mineStarted=0,mineDuration=0,yaw=0,pitch=-.12,velocityY=0,grounded=false,jumpLatch=false,lastChatId=0,lastFrame=performance.now(),playSeconds=0,saveTimer;

const scene=new THREE.Scene();scene.background=new THREE.Color(0x83c9eb);scene.fog=new THREE.Fog(0x83c9eb,42,125);
const camera=new THREE.PerspectiveCamera(72,1,.05,220);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.outputColorSpace=THREE.SRGBColorSpace;
const host=$('gameCanvas');host.innerHTML='';host.appendChild(renderer.domElement);const canvas=renderer.domElement;
const worldGroup=new THREE.Group(),decoGroup=new THREE.Group(),playerGroup=new THREE.Group();scene.add(worldGroup,decoGroup,playerGroup);
scene.add(new THREE.HemisphereLight(0xeafaff,0x31553c,1.8));const sun=new THREE.DirectionalLight(0xfff1cf,2.2);sun.position.set(35,55,20);scene.add(sun);
const cube=new THREE.BoxGeometry(1,1,1), materials={};for(const[t,d]of Object.entries(TYPES))materials[t]=new THREE.MeshStandardMaterial({color:d.color,roughness:.86,transparent:t==='glass',opacity:t==='glass'?.5:1,metalness:t==='gold'?.2:0});

async function api(url,opt={}){const r=await fetch(url,{credentials:'include',...opt});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);return d;}
function toast(msg){const e=$('toast');if(!e)return;e.textContent=msg;e.className='toast show';clearTimeout(window.__vToast);window.__vToast=setTimeout(()=>e.className='toast',1800);}
function resize(){const w=host.clientWidth||innerWidth,h=host.clientHeight||innerHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)}addEventListener('resize',resize);resize();
function rnd(x,z,s){const n=Math.sin(x*127.1+z*311.7+s*.731)*43758.5453;return n-Math.floor(n)}
function heightAt(x,z,s){return Math.max(2,Math.floor(3+rnd(Math.floor(x)*3,Math.floor(z)*5,s)*3));}
function addBlock(x,y,z,type){if(y<0||y>64||blocks.has(K(x,y,z))||!TYPES[type])return;const m=new THREE.Mesh(cube,materials[type]);m.position.set(x,y,z);m.userData={x,y,z,type};worldGroup.add(m);blocks.set(K(x,y,z),m)}
function removeBlock(x,y,z){const m=blocks.get(K(x,y,z));if(m){worldGroup.remove(m);blocks.delete(K(x,y,z))}}
function clearWorld(){for(const m of blocks.values())worldGroup.remove(m);blocks.clear();while(decoGroup.children.length)decoGroup.remove(decoGroup.children[0])}
function topAt(x,z){x=Math.round(x);z=Math.round(z);for(let y=64;y>=0;y--)if(blocks.has(K(x,y,z)))return y;return -1}
function generateWorld(){clearWorld();const seed=Number(meta.seed||1337),r=25;for(let x=-r;x<=r;x++)for(let z=-r;z<=r;z++){if(Math.hypot(x,z)>r+1)continue;const h=heightAt(x,z,seed);for(let y=0;y<=h;y++)addBlock(x,y,z,y===h?'grass':y>=h-2?'dirt':'stone')}for(let i=0;i<25;i++){const x=Math.floor(rnd(i*4,seed,seed)*42)-21,z=Math.floor(rnd(seed,i*7,seed+7)*42)-21,y=topAt(x,z)+1;if(y<1)continue;const g=new THREE.Group();const tr=new THREE.Mesh(new THREE.CylinderGeometry(.28,.4,2.7,7),new THREE.MeshStandardMaterial({color:0x765039}));const lf=new THREE.Mesh(new THREE.IcosahedronGeometry(1.45,1),materials.leaf);tr.position.y=1.35;lf.position.y=3;g.add(tr,lf);g.position.set(x,y,z);decoGroup.add(g)}}
function loadBlocks(list){clearWorld();if(Array.isArray(list)&&list.length){for(const b of list)addBlock(+b.x,+b.y,+b.z,b.type)}else generateWorld()}
function solid(x,y,z){return blocks.has(K(Math.floor(x),Math.floor(y),Math.floor(z)))}
function collides(px,eyeY,pz){const r=.29,feet=eyeY-1.62+.04,head=eyeY-.08;for(let x=Math.floor(px-r+.5);x<=Math.floor(px+r+.5);x++)for(let z=Math.floor(pz-r+.5);z<=Math.floor(pz+r+.5);z++)for(let y=Math.floor(feet+.5);y<=Math.floor(head+.5);y++)if(solid(x,y,z))return true;return false}
function spawn(){const t=topAt(0,4);camera.position.set(0,(t>=0?t+.5:3)+1.62,4);yaw=0;pitch=-.12;velocityY=0;grounded=true;look()}
function look(){camera.rotation.order='YXZ';camera.rotation.y=yaw;camera.rotation.x=pitch}
function move(dt){if(!started||paused)return;const f=new THREE.Vector3(-Math.sin(yaw),0,-Math.cos(yaw)),r=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw)),d=new THREE.Vector3();if(keys.has('w'))d.add(f);if(keys.has('s'))d.sub(f);if(keys.has('d'))d.add(r);if(keys.has('a'))d.sub(r);if(d.lengthSq())d.normalize();if(mode==='creative'){const speed=keys.has('shift')?9:6;camera.position.x+=d.x*speed*dt;camera.position.z+=d.z*speed*dt;if(keys.has(' '))camera.position.y+=speed*dt;if(keys.has('control'))camera.position.y-=speed*dt}else{const speed=keys.has('shift')?7:4.6;const nx=camera.position.x+d.x*speed*dt,nz=camera.position.z+d.z*speed*dt;if(!collides(nx,camera.position.y,camera.position.z))camera.position.x=nx;if(!collides(camera.position.x,camera.position.y,nz))camera.position.z=nz;const jump=keys.has(' ');if(jump&&!jumpLatch&&grounded){velocityY=7.2;grounded=false}jumpLatch=jump;velocityY-=20*dt;const ny=camera.position.y+velocityY*dt;if(!collides(camera.position.x,ny,camera.position.z))camera.position.y=ny;else if(velocityY<0){const t=topAt(camera.position.x,camera.position.z);if(t>=0)camera.position.y=t+.5+1.62;velocityY=0;grounded=true}else velocityY=0}camera.position.x=THREE.MathUtils.clamp(camera.position.x,-63,63);camera.position.z=THREE.MathUtils.clamp(camera.position.z,-63,63);camera.position.y=THREE.MathUtils.clamp(camera.position.y,1.8,64);if($('worldCoords'))$('worldCoords').textContent=`X ${Math.round(camera.position.x)} · Y ${Math.round(camera.position.y-1.62)} · Z ${Math.round(camera.position.z)}`}
function rayHit(){const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2(0,0),camera);return ray.intersectObjects([...blocks.values()],false).find(h=>h.distance<=7)||null}
function startMine(){const h=rayHit();if(!h)return;mineTarget=h.object;mineStarted=performance.now();mineDuration=Math.max(120,(TYPES[h.object.userData.type]?.hard||.5)*520);$('breakMeter')?.classList.add('on')}
function updateMine(now){if(!mining){$('breakMeter')?.classList.remove('on');return}const h=rayHit();if(!h||h.object!==mineTarget){if(h)startMine();return}const p=Math.min(1,(now-mineStarted)/mineDuration);if($('breakMeterFill'))$('breakMeterFill').style.width=`${p*100}%`;if(p>=1){const b=mineTarget.userData;if(b.y>0){removeBlock(b.x,b.y,b.z);if(mode==='survival')inventory[b.type]++;dirty();toast(`${TYPES[b.type].name} collected`)}mineTarget=null;$('breakMeter')?.classList.remove('on')}}
function place(){const h=rayHit();if(!h)return;const type=HOT[selected];if(mode!=='creative'&&!inventory[type])return toast(`No ${TYPES[type].name} in bag`);const n=h.face?.normal?.clone()||new THREE.Vector3(0,1,0),p=h.object.position.clone().add(n),x=Math.round(p.x),y=Math.round(p.y),z=Math.round(p.z);if(y<0||y>64||blocks.has(K(x,y,z))||collides(x,camera.position.y,z))return;addBlock(x,y,z,type);if(mode!=='creative')inventory[type]--;dirty()}
function dirty(){clearTimeout(saveTimer);if($('saveState')){$('saveState').textContent='UNSAVED';$('saveState').classList.remove('sync')}renderHotbar();saveTimer=setTimeout(saveWorld,1400)}
async function saveWorld(){try{const payload=[...blocks.values()].map(m=>m.userData);await api(`/api/worlds/state?id=${encodeURIComponent(worldId)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({blocks:payload})});if($('saveState')){$('saveState').textContent='SYNCED';$('saveState').classList.add('sync')}}catch(e){toast('World tersimpan lokal; server belum siap')}}
function color(n){return '#'+n.toString(16).padStart(6,'0')}
function renderHotbar(){const root=$('hotbar');if(!root)return;root.innerHTML='';HOT.forEach((t,i)=>{const b=document.createElement('button');b.type='button';b.className=`slot ${i===selected?'selected':''}`;b.innerHTML=`<span class="num">${i+1}</span><i class="swatch" style="background:${color(TYPES[t].color)}"></i><span class="count">${mode==='creative'?'∞':inventory[t]||0}</span>`;b.onclick=e=>{e.stopPropagation();selected=i;renderHotbar()};root.appendChild(b)})}
function renderInventory(){const root=$('inventoryGrid');if(!root)return;root.innerHTML='';Object.keys(TYPES).forEach(t=>{const b=document.createElement('button');b.type='button';b.className='inv-slot';b.innerHTML=`<i style="background:${color(TYPES[t].color)}"></i><strong>${TYPES[t].name}</strong><small>${mode==='creative'?'Unlimited':`${inventory[t]||0} items`}</small>`;b.onclick=()=>{const i=HOT.indexOf(t);if(i>=0)selected=i;closeInventory();renderHotbar()};root.appendChild(b)})}
function release(){if(document.pointerLockElement===canvas)document.exitPointerLock();canvas.style.cursor='default'}
function capture(){if(!started||paused||chatOpen)return;try{canvas.requestPointerLock()}catch{} }
function openInventory(){if(!started)return;release();paused=true;$('inventoryPanel').hidden=false;$('pausePanel').hidden=true;renderInventory()}
function closeInventory(){ $('inventoryPanel').hidden=true;paused=false }
function openPause(){if(!started||chatOpen)return;release();paused=true;$('pausePanel').hidden=false;$('inventoryPanel').hidden=true}
function closePause(){paused=false;$('pausePanel').hidden=true;capture()}
function openChat(){if(!started)return;release();chatOpen=true;paused=true;$('chatPanel').classList.add('open');setTimeout(()=>$('worldChatInput').focus(),30)}
function closeChat(){chatOpen=false;paused=false;$('chatPanel').classList.remove('open');capture()}
function toggleMode(){mode=mode==='creative'?'survival':'creative';$('modeButton').textContent=mode.toUpperCase();$('worldType').textContent=mode.toUpperCase();renderHotbar();renderInventory();toast(mode.toUpperCase())}
async function pollChat(){try{const d=await api(`/api/chat?worldId=${encodeURIComponent(worldId)}&after=${lastChatId}`);for(const m of d.messages||[]){lastChatId=Math.max(lastChatId,Number(m.id||0));const e=document.createElement('div');e.className='msg';e.innerHTML=`<b>@${String(m.username||'Explorer').replace(/[<>]/g,'')}</b><span>${String(m.message||'').replace(/[<>]/g,'')}</span>`;$('worldChatMessages').appendChild(e)}$('worldChatMessages').scrollTop=$('worldChatMessages').scrollHeight}catch{}}
async function sendChat(){const input=$('worldChatInput'),message=input.value.trim();if(!message)return;try{await api(`/api/chat?worldId=${encodeURIComponent(worldId)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message})});input.value='';pollChat()}catch{toast('Chat belum tersambung')}}
async function load(){try{if(worldId){try{const d=await api(`/api/worlds?id=${encodeURIComponent(worldId)}`);if(d.world)meta=d.world;else if(d.worlds)meta=d.worlds.find(w=>w.id===worldId)||meta}catch(e){console.warn('world metadata fallback',e)}mode=meta.type==='creative'?'creative':'survival';$('worldName').textContent=meta.name;$('startWorldName').textContent=meta.name;$('worldType').textContent=mode.toUpperCase();$('modeButton').textContent=mode.toUpperCase();let state=null;try{state=await api(`/api/worlds/state?id=${encodeURIComponent(worldId)}`)}catch(e){console.warn('state fallback',e)}loadBlocks(state?.blocks);spawn();renderHotbar();renderInventory();pollChat();$('fatal').hidden=true;$('startOverlay').classList.remove('hidden')}}catch(e){console.error(e);$('fatalText').textContent='Klik kembali ke Worlds lalu masuk lagi.';$('fatal').hidden=false}}
function start(){if(started)return;started=true;$('startOverlay').classList.add('hidden');$('status').textContent='CLICK WORLD · WASD MOVE · MOUSE LOOK';capture();toast('Klik area game untuk mulai melihat')}

$('playNow').onclick=start;$('modeButton').onclick=toggleMode;$('chatToggle').onclick=()=>chatOpen?closeChat():openChat();$('chatClose').onclick=closeChat;$('inventoryButton').onclick=openInventory;$('closeInventory').onclick=closeInventory;$('saveWorld').onclick=saveWorld;$('backHome').onclick=()=>{saveWorld();location.href='./dashboard.html'};$('resumeButton').onclick=closePause;$('pauseInventory').onclick=openInventory;$('pauseExit').onclick=()=>{saveWorld();location.href='./dashboard.html'};$('chatForm').addEventListener('submit',e=>{e.preventDefault();sendChat()});
canvas.addEventListener('click',()=>{if(started&&!paused&&!chatOpen)capture()});canvas.addEventListener('mousedown',e=>{if(!started||paused||chatOpen)return;if(e.button===0){mining=true;startMine()}else if(e.button===2){e.preventDefault();place()}});addEventListener('mouseup',e=>{if(e.button===0)mining=false});canvas.addEventListener('contextmenu',e=>e.preventDefault());
addEventListener('mousemove',e=>{if(document.pointerLockElement!==canvas||paused||chatOpen)return;yaw-=e.movementX*.0024;pitch=THREE.MathUtils.clamp(pitch-e.movementY*.0022,-1.48,1.48);look()});
addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement)return;const k=e.key.toLowerCase();if(k==='escape'){if(!$('inventoryPanel').hidden){closeInventory();capture()}else if(!$('pausePanel').hidden){closePause()}else if(chatOpen){closeChat()}else openPause();return}if(k==='e'){openInventory();return}if(k==='t'){openChat();return}if(['w','a','s','d',' ','shift','control'].includes(k)){e.preventDefault();keys.add(k)}if(/^\d$/.test(k)){const n=Number(k);if(n>=1&&n<=9){selected=n-1;renderHotbar()}}});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
document.addEventListener('pointerlockchange',()=>{if(document.pointerLockElement===canvas){$('status').textContent=mode==='creative'?'WASD MOVE · SPACE UP · SHIFT DOWN · MOUSE LOOK':'WASD MOVE · SPACE JUMP · SHIFT SPRINT · MOUSE LOOK';canvas.style.cursor='none'}else if(started&&!paused&&!chatOpen){$('status').textContent='CLICK WORLD TO LOOK';canvas.style.cursor='default'}});
setInterval(pollChat,2500);setInterval(()=>{if(started&&!paused&&!document.hidden)playSeconds+=2.5},2500);setInterval(()=>{if(playSeconds>=1){const s=Math.floor(playSeconds);playSeconds-=s;fetch('/api/activity',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({seconds:s})}).catch(()=>{})}},10000);
function loop(now){const dt=Math.min(.05,(now-lastFrame)/1000);lastFrame=now;move(dt);updateMine(now);renderer.render(scene,camera);requestAnimationFrame(loop)}
load();requestAnimationFrame(loop);
