import * as THREE from 'https://esm.sh/three@0.180.0';
import { PointerLockControls } from 'https://esm.sh/three@0.180.0/examples/jsm/controls/PointerLockControls.js';

const params=new URLSearchParams(location.search),worldId=params.get('id');
if(!worldId)location.href='./dashboard.html';
const $=id=>document.getElementById(id);
const host=$('gameCanvas'),shell=$('gameShell'),worldNameEl=$('worldName'),worldTypeEl=$('worldType'),saveStateEl=$('saveState'),statusEl=$('actionStatus'),coordsEl=$('worldCoords'),locationEl=$('locationName'),toastEl=$('toast'),hotbarEl=$('hotbar'),breakMeter=$('breakMeter'),breakFill=breakMeter.querySelector('span'),targetHint=$('targetHint'),inventoryPanel=$('inventoryPanel'),inventoryGrid=$('inventoryGrid'),recipeGrid=$('recipeGrid'),modeButton=$('modeButton'),modeLabel=$('modeLabel'),startOverlay=$('startOverlay'),pausePanel=$('pausePanel');
const blockNames={grass:'Grass',dirt:'Dirt',stone:'Stone',wood:'Wood',leaf:'Leaves',sand:'Sand',crystal:'Vexa Crystal',gold:'Vexa Ore',glass:'Glass',brick:'Brick'};
const colors={grass:0x59bd70,dirt:0x8b5a3c,stone:0x89939f,wood:0x9b6941,leaf:0x3d9658,sand:0xd8bd74,crystal:0x68d9e8,gold:0xe4b43d,glass:0x9ddff1,brick:0xa64f47};
const hardness={grass:.25,dirt:.35,sand:.25,leaf:.18,wood:.7,stone:.9,crystal:1.2,gold:1.5,glass:.18,brick:.8};
const hotbar=['grass','dirt','stone','wood','leaf','sand','crystal','gold','brick'];
const inventory=Object.fromEntries(Object.keys(blockNames).map(k=>[k,0]));
const blocks=new Map(),key=(x,y,z)=>`${x},${y},${z}`;
let world=null,mode='survival',selected=0,dirty=false,saveTimer=null,toastTimer=null,last=performance.now(),clock=.18,health=100,hunger=100,velocityY=0,onGround=false,pointerLocked=false,mineTarget=null,mineStart=0,mineDuration=0,mineDown=false,jumpDown=false;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function toast(m,k='success'){toastEl.textContent=m;toastEl.className=`game-toast show ${k}`;clearTimeout(toastTimer);toastTimer=setTimeout(()=>toastEl.className='game-toast',2200)}
function dirtyState(v){dirty=v;saveStateEl.textContent=v?'UNSAVED':'SYNCED';saveStateEl.classList.toggle('dirty',v);saveStateEl.classList.remove('error')}
async function api(url,opt={}){const r=await fetch(url,{credentials:'include',...opt});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Request failed');return d}

const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(75,1,.05,180),renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});
scene.background=new THREE.Color(0x86c5e0);scene.fog=new THREE.FogExp2(0x86c5e0,.0105);renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;host.appendChild(renderer.domElement);
const controls=new PointerLockControls(camera,renderer.domElement);
const hemi=new THREE.HemisphereLight(0xdff7ff,0x263746,1.65);scene.add(hemi);const sun=new THREE.DirectionalLight(0xfff1cf,2.8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun);const moon=new THREE.DirectionalLight(0x7898ff,.3);scene.add(moon);
const geo=new THREE.BoxGeometry(1,1,1),materials={};for(const [n,c] of Object.entries(colors))materials[n]=new THREE.MeshStandardMaterial({color:c,roughness:n==='glass'?.2:.9,transparent:n==='glass',opacity:n==='glass'?.52:1,metalness:n==='gold'?.15:0,emissive:n==='crystal'?0x0b667d:n==='gold'?0x3a2b08:0,emissiveIntensity:n==='crystal'?.65:n==='gold'?.18:0});
function noise(x,z,s){const q=Math.sin(x*127.1+z*311.7+s*.731)*43758.5453;return q-Math.floor(q)}function sn(x,z,s){const x0=Math.floor(x),z0=Math.floor(z),xf=x-x0,zf=z-z0,u=xf*xf*(3-2*xf),v=zf*zf*(3-2*zf),a=noise(x0,z0,s),b=noise(x0+1,z0,s),c=noise(x0,z0+1,s),d=noise(x0+1,z0+1,s);return THREE.MathUtils.lerp(THREE.MathUtils.lerp(a,b,u),THREE.MathUtils.lerp(c,d,u),v)}
function height(x,z,s){return Math.max(2,Math.floor(3+sn(x*.11,z*.11,s)*3.2+sn(x*.27,z*.27,s+91)*1.4+Math.abs(Math.sin((x+s%31)*.075)+Math.cos((z-s%19)*.065))*1.1))}
function add(x,y,z,type){const id=key(x,y,z);if(blocks.has(id))return false;const m=new THREE.Mesh(geo,materials[type]||materials.grass);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;m.userData={x,y,z,type};scene.add(m);blocks.set(id,m);return true}
function remove(m){if(!m||m.userData.y<=0)return null;const b=m.userData;scene.remove(m);blocks.delete(key(b.x,b.y,b.z));return b}
function top(x,z){let y=-1;for(let i=0;i<70;i++)if(blocks.has(key(Math.round(x),i,Math.round(z))))y=i;return y}
function ground(x,z){const y=top(x,z);return(y>=0?y+1:height(Math.round(x),Math.round(z),world?.seed||1))+1.65}

const scenery=new THREE.Group();scene.add(scenery),critters=[];
function clearScenery(){scenery.clear();critters.length=0}
function tree(x,z){const y=top(x,z)+1;if(y<1)return;const g=new THREE.Group(),tr=new THREE.Mesh(new THREE.BoxGeometry(.72,3.1,.72),new THREE.MeshStandardMaterial({color:0x795033}));tr.position.y=1.55;tr.castShadow=true;g.add(tr);for(const [a,b,c,s] of [[0,3.2,0,1.45],[-.8,2.9,.1,1],[.8,2.9,-.1,1],[0,4,.0,.85]]){const l=new THREE.Mesh(new THREE.IcosahedronGeometry(s,1),materials.leaf);l.position.set(a,b,c);l.castShadow=true;g.add(l)}g.position.set(x,y,z);scenery.add(g)}
function critter(x,z,i){const y=top(x,z)+1;if(y<1)return;const g=new THREE.Group(),mat=new THREE.MeshStandardMaterial({color:[0x8e75c7,0x67b8a1,0xe2a35e][i%3]});const body=new THREE.Mesh(new THREE.BoxGeometry(.9,.62,1.25),mat),head=new THREE.Mesh(new THREE.BoxGeometry(.55,.55,.6),mat);body.position.y=.65;head.position.set(0,.82,-.72);g.add(body,head);const eye=new THREE.MeshBasicMaterial({color:0x11121b});for(const sx of[-.14,.14]){const e=new THREE.Mesh(new THREE.SphereGeometry(.045,8,8),eye);e.position.set(sx,.92,-1.02);g.add(e)}g.position.set(x,y,z);scenery.add(g);critters.push({g,x,z,p:i*1.7,s:.18+i%3*.06})}
function decorate(){clearScenery();const s=world.seed;for(let i=0;i<28;i++){const x=Math.floor(noise(i*4,s,s)*43)-21,z=Math.floor(noise(s,i*7,s+7)*43)-21;if(Math.abs(x)<4&&Math.abs(z)<5)continue;tree(x,z)}for(let i=0;i<9;i++){const x=Math.floor(noise(i*13,s,s+31)*42)-21,z=Math.floor(noise(s,i*11,s+33)*42)-21;critter(x,z,i)}const water=new THREE.Mesh(new THREE.CircleGeometry(8,48),new THREE.MeshStandardMaterial({color:0x3eb9d8,transparent:true,opacity:.72,roughness:.15}));water.rotation.x=-Math.PI/2;water.scale.set(1.4,.8,1);water.position.set(11,4.05,-10);scenery.add(water)}
function generate(){for(const m of blocks.values())scene.remove(m);blocks.clear();const s=world.seed,r=24;for(let x=-r;x<=r;x++)for(let z=-r;z<=r;z++){if(Math.hypot(x,z)>r+1)continue;const h=height(x,z,s);for(let y=0;y<=h;y++){let t=y===h?'grass':y>=h-2?'dirt':'stone';if(y<2&&noise(x,z,s+3)>.9)t='gold';if(y===h&&noise(x,z,s+4)>.96)t='crystal';add(x,y,z,t)}}decorate()}
function buildSky(){const sky=new THREE.Mesh(new THREE.SphereGeometry(110,32,16),new THREE.MeshBasicMaterial({color:0x7eb9d6,side:THREE.BackSide}));scene.add(sky);const p=[];for(let i=0;i<550;i++){const v=new THREE.Vector3((Math.random()-.5)*170,25+Math.random()*65,(Math.random()-.5)*170);p.push(v.x,v.y,v.z)}const stars=new THREE.Points(new THREE.BufferGeometry(),new THREE.PointsMaterial({color:0xffffff,size:.14,transparent:true,opacity:0}));stars.geometry.setAttribute('position',new THREE.Float32BufferAttribute(p,3));stars.userData.stars=true;scene.add(stars)}buildSky();

function renderHotbar(){hotbarEl.innerHTML='';hotbar.forEach((t,i)=>{const b=document.createElement('button');b.className=`hot-slot ${i===selected?'selected':''}`;b.innerHTML=`<span class="slot-number">${i+1}</span><span class="voxel-icon voxel-${t}"></span><b class="count">${mode==='creative'?'∞':inventory[t]||0}</b>`;b.onclick=()=>selectSlot(i);hotbarEl.appendChild(b)})}
function selectSlot(i){selected=clamp(i,0,8);renderHotbar();targetHint.textContent=`${blockNames[hotbar[selected]]} · RMB to place`}
function renderInventory(){inventoryGrid.innerHTML='';Object.keys(blockNames).forEach(t=>{const b=document.createElement('button');b.className='inv-slot';b.innerHTML=`<span class="voxel-icon voxel-${t}"></span><b>${mode==='creative'?'∞':inventory[t]||0}</b>`;b.title=blockNames[t];b.onclick=()=>{const i=hotbar.indexOf(t);if(i>=0)selectSlot(i);closeInventory()};inventoryGrid.appendChild(b)});recipeGrid.innerHTML='';const recipes=[['Planks','wood',1,'wood',4],['Glass','sand',4,'glass',1],['Brick','stone',2,'brick',1],['Crystal Block','crystal',2,'crystal',1],['Vexa Ingot','gold',3,'gold',1]];for(const [name,need,n,give,out] of recipes){const can=mode==='creative'||(inventory[need]||0)>=n;const b=document.createElement('button');b.className='recipe';b.disabled=!can;b.innerHTML=`<span class="voxel-icon voxel-${give}"></span><span><strong>${name}</strong><small>${n} × ${blockNames[need]} → ${out}</small></span>`;b.onclick=()=>{if(mode!=='creative'){inventory[need]-=n;inventory[give]+=out}renderInventory();renderHotbar();toast(`${name} crafted`)};recipeGrid.appendChild(b)}$('craftHint').textContent=mode==='creative'?'Creative mode: every block is unlimited.':'Mine resources and turn them into building materials.'}
function openInventory(){inventoryPanel.hidden=false;renderInventory();controls.unlock()}function closeInventory(){inventoryPanel.hidden=true}
function setMode(m){mode=m;modeButton.textContent=m.toUpperCase();modeLabel.textContent=m.toUpperCase();worldTypeEl.textContent=m.toUpperCase();if(m==='creative'){health=100;hunger=100;toast('Creative: unlimited blocks + flight')}else toast('Survival: gather, craft and build');renderHotbar();renderInventory()}
function collect(t){if(mode==='survival'){inventory[t]=(inventory[t]||0)+1;renderHotbar()}}
function canPlace(t){return mode==='creative'||(inventory[t]||0)>0}
function consume(t){if(mode==='creative')return true;if(!canPlace(t)){toast(`No ${blockNames[t]} left`,'error');return false}inventory[t]--;renderHotbar();return true}

const ray=new THREE.Raycaster();function hit(){ray.setFromCamera(new THREE.Vector2(0,0),camera);return ray.intersectObjects([...blocks.values()],false).find(h=>h.distance<=7)||null}
function beginMine(){const h=hit();if(!h)return;mineTarget=h.object;mineStart=performance.now();mineDuration=Math.max(160,hardness[h.object.userData.type]*650);breakMeter.style.display='block';statusEl.textContent=`MINING ${blockNames[h.object.userData.type].toUpperCase()}`}
function stopMine(){mineTarget=null;breakMeter.style.display='none';breakFill.style.width='0';statusEl.textContent='WORLD ONLINE'}
function updateMine(now){if(!mineDown){if(mineTarget)stopMine();return}const h=hit();if(!h||h.object!==mineTarget){stopMine();if(h)beginMine();return}const p=clamp((now-mineStart)/mineDuration,0,1);breakFill.style.width=`${p*100}%`;if(p>=1){const b=remove(mineTarget);if(b){collect(b.type);dirtyState(true);toast(`${blockNames[b.type]} collected`);scheduleSave()}stopMine()}}
function place(){const h=hit();if(!h)return;const t=hotbar[selected];if(!consume(t))return;const n=h.face.normal.clone().transformDirection(h.object.matrixWorld),p=h.object.position.clone().add(n.multiplyScalar(1.01));const x=Math.round(p.x),y=Math.round(p.y),z=Math.round(p.z);if(y<0||y>63||Math.abs(x)>28||Math.abs(z)>28){toast('Build limit reached','error');if(mode!=='creative')inventory[t]++;renderHotbar();return}if(add(x,y,z,t)){dirtyState(true);toast(`${blockNames[t]} placed`);scheduleSave()}else if(mode!=='creative'){inventory[t]++;renderHotbar()}}

const keys=new Set();
function collides(x,y,z){const r=.28,b=y-1.6,t=y-.08;for(const [dx,dz] of[[-r,-r],[r,-r],[-r,r],[r,r]])if(blocks.has(key(Math.floor(x+dx),Math.floor(b),Math.floor(z+dz)))||blocks.has(key(Math.floor(x+dx),Math.floor(t),Math.floor(z+dz))))return true;return false}
function move(dt){if(!pointerLocked)return;const f=new THREE.Vector3();camera.getWorldDirection(f);f.y=0;f.normalize();const r=new THREE.Vector3().crossVectors(f,new THREE.Vector3(0,1,0)).normalize(),v=new THREE.Vector3();if(keys.has('w'))v.add(f);if(keys.has('s'))v.sub(f);if(keys.has('d'))v.add(r);if(keys.has('a'))v.sub(r);const moving=v.lengthSq()>0;if(moving)v.normalize();const sprint=keys.has('shift')&&mode==='survival'&&moving;const crouch=keys.has('control');const speed=mode==='creative'?(keys.has('shift')?14:8):(sprint?8:5.2)*(crouch?.55:1);if(mode==='creative'){if(keys.has(' '))camera.position.y+=speed*dt;if(keys.has('control'))camera.position.y-=speed*dt;camera.position.addScaledVector(v,speed*dt)}else{const ox=camera.position.x,oz=camera.position.z;camera.position.x+=v.x*speed*dt;if(collides(camera.position.x,camera.position.y,camera.position.z))camera.position.x=ox;camera.position.z+=v.z*speed*dt;if(collides(camera.position.x,camera.position.y,camera.position.z))camera.position.z=oz;if(keys.has(' ')&&!jumpDown&&onGround){velocityY=7.4;onGround=false}velocityY-=19*dt;camera.position.y+=velocityY*dt;const gy=ground(camera.position.x,camera.position.z);if(camera.position.y<=gy){camera.position.y=gy;velocityY=0;onGround=true}else onGround=false;hunger=clamp(hunger-dt*(moving?.16:.035),0,100)}jumpDown=keys.has(' ');camera.position.x=clamp(camera.position.x,-27,27);camera.position.z=clamp(camera.position.z,-27,27);camera.position.y=clamp(camera.position.y,1.8,63);coordsEl.textContent=`X ${Math.round(camera.position.x)} · Y ${Math.round(camera.position.y-1.65)} · Z ${Math.round(camera.position.z)}`;locationEl.textContent=camera.position.x>7&&camera.position.z<-6?'SUNSET LAKE':camera.position.x<-8&&camera.position.z>8?'WILLOW WOODS':camera.position.z<-10?'CRYSTAL RIDGE':camera.position.x>10?'VEXA COAST':'VEXA MEADOWS'}
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys.add(k);if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();const n=Number(e.key);if(n>=1&&n<=9)selectSlot(n-1);if(k==='e'&&!e.repeat){inventoryPanel.hidden?openInventory():closeInventory()}if(k==='escape'&&!inventoryPanel.hidden)closeInventory()});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));renderer.domElement.addEventListener('mousedown',e=>{if(!pointerLocked)return;if(e.button===0){mineDown=true;beginMine()}if(e.button===2)place()});window.addEventListener('mouseup',e=>{if(e.button===0)mineDown=false});renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());
controls.addEventListener('lock',()=>{pointerLocked=true;targetHint.style.opacity='0';startOverlay.style.display='none';pausePanel.hidden=true});controls.addEventListener('unlock',()=>{pointerLocked=false;targetHint.style.opacity='.95';if(startOverlay.style.display==='none'&&inventoryPanel.hidden)pausePanel.hidden=false});$('playNow').onclick=()=>controls.lock();$('resumeButton').onclick=()=>controls.lock();$('inventoryButton').onclick=openInventory;$('closeInventory').onclick=closeInventory;$('pauseInventory').onclick=()=>{pausePanel.hidden=true;openInventory()};$('pauseExit').onclick=()=>location.href='./dashboard.html';$('backHome').onclick=()=>{if(dirty)saveWorld();location.href='./dashboard.html'};$('saveWorld').onclick=saveWorld;modeButton.onclick=()=>setMode(mode==='creative'?'survival':'creative');
function serialize(){return [...blocks.values()].map(m=>m.userData)}async function saveWorld(){if(!dirty){toast('World is already synced');return}saveStateEl.textContent='SAVING…';try{const d=await api(`/api/worlds/state?id=${encodeURIComponent(worldId)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({blocks:serialize()})});dirtyState(false);toast(`World saved · ${d.saved} blocks`)}catch(e){saveStateEl.textContent='SYNC ERROR';toast(e.message,'error')}}function scheduleSave(){clearTimeout(saveTimer);saveTimer=setTimeout(saveWorld,2200)}
async function load(){try{world=(await api(`/api/worlds?id=${encodeURIComponent(worldId)}`)).world;worldNameEl.textContent=world.name;$('startWorldName').textContent=`${world.name} awaits.`;const me=await api('/api/auth/me');$('playerName').textContent=me.user?.displayName||me.user?.username||'Explorer';const state=await api(`/api/worlds/state?id=${encodeURIComponent(worldId)}`);if(state.blocks?.length){for(const b of state.blocks)add(Number(b.x),Number(b.y),Number(b.z),String(b.type));decorate()}else generate();setMode(world.type==='creative'?'creative':'survival');camera.position.set(0,ground(0,5),5);dirtyState(false)}catch(e){toast(e.message,'error');saveStateEl.textContent='LOAD ERROR'}}
function dayNight(dt){clock=(clock+dt*.008)%1;const a=clock*Math.PI*2,y=Math.sin(a),x=Math.cos(a),light=clamp(y*.65+.48,.12,1);sun.position.set(x*35,Math.max(-4,y*45),18);sun.intensity=light*3;hemi.intensity=.65+light;moon.intensity=(1-light)*.55;const c=new THREE.Color().setHSL(.56,.43,.15+light*.28);scene.background.lerp(c,.035);scene.fog.color.copy(scene.background);const stars=scene.children.find(o=>o.userData?.stars);if(stars)stars.material.opacity=(1-light)*.85;$('dayText').textContent=`DAY ${Math.floor(clock*24/24)+1}`;if(mode==='survival'){if(hunger<=0)health=clamp(health-dt*.45,0,100);if(health<=0){health=100;hunger=80;camera.position.set(0,ground(0,5),5);toast('You fainted and respawned','error')}}$('healthBar').style.width=`${health}%`;$('hungerBar').style.width=`${hunger}%`;$('healthText').textContent=Math.round(health);$('hungerText').textContent=Math.round(hunger)}
function updateCritters(t){for(const c of critters){c.g.position.x=c.x+Math.sin(t*c.s+c.p)*2.3;c.g.position.z=c.z+Math.cos(t*c.s*.8+c.p)*1.8;c.g.position.y=top(c.g.position.x,c.g.position.z)+1;c.g.rotation.y=Math.sin(t*c.s+c.p)}}
function resize(){const w=host.clientWidth,h=host.clientHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)}window.addEventListener('resize',resize);resize();selectSlot(0);load();
function loop(now){requestAnimationFrame(loop);const dt=Math.min(.05,(now-last)/1000);last=now;move(dt);updateMine(now);dayNight(dt);updateCritters(now/1000);renderer.render(scene,camera)}loop(performance.now());
