const {randomUUID}=require('crypto'); const {initDb}=require('./_lib/db'); const {getSessionUserId}=require('./_lib/auth'); const {getItem}=require('../data/items');
module.exports=async function(req,res){const uid=getSessionUserId(req);if(!uid)return res.status(401).json({error:'Authentication required.'});try{const db=await initDb();
if(req.method==='GET'){const rows=await db.execute({sql:`SELECT s.id,s.item_id,s.quantity,s.price,s.currency,s.owner_id,s.world_id,u.username owner_username FROM shop_listings s JOIN users u ON u.id=s.owner_id WHERE s.active=1 ORDER BY s.created_at DESC LIMIT 100`,args:[]});return res.status(200).json({listings:rows.rows});}
if(req.method==='POST'){const action=String(req.body?.action||'');if(action==='list'){const itemId=String(req.body?.itemId||'');const qty=Math.floor(Number(req.body?.quantity));const price=Math.floor(Number(req.body?.price));const currency=['gems','world_coins'].includes(req.body?.currency)?req.body.currency:'gems';if(!getItem(itemId)||!Number.isInteger(qty)||qty<1||qty>10000||!Number.isInteger(price)||price<0)return res.status(400).json({error:'Invalid listing.'});const have=await db.execute({sql:'SELECT quantity FROM player_inventory WHERE user_id=? AND item_id=? LIMIT 1',args:[uid,itemId]});if(!have.rows[0]||Number(have.rows[0].quantity)<qty)return res.status(400).json({error:'Not enough items.'});const id=randomUUID();
const tx=await db.transaction('write');
try {
  const removed=await tx.execute({sql:'UPDATE player_inventory SET quantity=quantity-?,updated_at=datetime(\'now\') WHERE user_id=? AND item_id=? AND quantity>=?',args:[qty,uid,itemId,qty]});
  if(Number(removed.rowsAffected||0)!==1){await tx.rollback();return res.status(409).json({error:'Item stock changed. Try again.'});}
  await tx.execute({sql:'INSERT INTO shop_listings(id,owner_id,world_id,item_id,quantity,price,currency) VALUES(?,?,?,?,?,?,?)',args:[id,uid,req.body?.worldId||null,itemId,qty,price,currency]});
  await tx.commit(); return res.status(201).json({id});
} catch(e){try{await tx.rollback()}catch{}throw e;}}
if(action==='buy'){const id=String(req.body?.listingId||'');const listing=await db.execute({sql:'SELECT * FROM shop_listings WHERE id=? AND active=1 LIMIT 1',args:[id]});if(!listing.rows[0])return res.status(404).json({error:'Listing not found.'});const l=listing.rows[0];if(l.owner_id===uid)return res.status(400).json({error:'You cannot buy your own listing.'});const tx=await db.transaction('write');try{await tx.execute({sql:'INSERT OR IGNORE INTO player_wallets(user_id) VALUES(?)',args:[uid]});const wallet=await tx.execute({sql:'SELECT gems,world_coins FROM player_wallets WHERE user_id=? LIMIT 1',args:[uid]});const bal=Number(wallet.rows[0]?.[l.currency]||0);if(bal<Number(l.price)){await tx.rollback();return res.status(400).json({error:'Not enough currency.'});}const removed=await tx.execute({sql:'UPDATE player_inventory SET quantity=quantity-?,updated_at=datetime(\'now\') WHERE user_id=? AND item_id=? AND quantity>=?',args:[l.quantity,l.owner_id,l.item_id,l.quantity]});if(Number(removed.rowsAffected)!==1){await tx.rollback();return res.status(409).json({error:'Seller no longer has those items.'});}await tx.execute({sql:'UPDATE player_wallets SET '+(l.currency==='gems'?'gems':'world_coins')+'='+(l.currency==='gems'?'gems':'world_coins')+'-?,updated_at=datetime(\'now\') WHERE user_id=?',args:[l.price,uid]});await tx.execute({sql:'INSERT INTO player_inventory(user_id,item_id,quantity) VALUES(?,?,?) ON CONFLICT(user_id,item_id) DO UPDATE SET quantity=quantity+excluded.quantity,updated_at=datetime(\'now\')',args:[uid,l.item_id,l.quantity]});await tx.execute({sql:'INSERT OR IGNORE INTO player_wallets(user_id) VALUES(?)',args:[l.owner_id]});await tx.execute({sql:'UPDATE player_wallets SET '+(l.currency==='gems'?'gems':'world_coins')+'='+(l.currency==='gems'?'gems':'world_coins')+'+?,updated_at=datetime(\'now\') WHERE user_id=?',args:[l.price,l.owner_id]});await tx.execute({sql:'UPDATE shop_listings SET active=0,updated_at=datetime(\'now\') WHERE id=? AND active=1',args:[id]});await tx.commit();return res.status(200).json({bought:true});}catch(e){try{await tx.rollback()}catch{}throw e;}}
return res.status(400).json({error:'Unknown shop action.'});}return res.status(405).json({error:'Method not allowed.'});}catch(e){console.error(e);return res.status(500).json({error:'Unable to access shop.'})}};